# Generated by Django 5.2.7 on 2025-10-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='laboratorio',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='laboratorio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salud_api.laboratorio'),
            preserve_default=False,
        ),
    ]
